version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/var/www/html
    ports:
      - "7000:8000"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "7001:8000"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "${MQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${MQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${MQ_VHOST}"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  rabbitmq:
    driver: local
