version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/var/www/html
    ports:
      - "7000:8000"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  transaction_create:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/var/www/html
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: php artisan transaction:create

  transaction_confirm:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/var/www/html
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: php artisan transaction:confirmation
